### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by rdso1984**
Translation of the lesson to Portuguese to help brazilian fellows to learn code.

### CODE REVIEW

**Comment by gj** [comment]
This is so cool @rdso1984 !

**Comment by rdso1984** [comment]
Thank you @gj. I would like that Brazilian students to learn to code easier, with good and simple lessons. It's not easy to find good materials like this one. I will try to translate all the lessons and find out how to share them.
I have asked to @jmburges if I could translate the lessons and he said OK:)

**Comment by Donnadieu** [comment]
@maxwellbenton what do you think we can do with this PR?

**Comment by maxwellbenton** [comment]
Hi @rdso1984,

Thank you for doing this translation! Unfortunately, since our master branch is used by all of our existing courses, we won't be able to merge this PR in. However, if you wanted to open a new PR, I've added a branch called `wip-portuguese` that this content could be merged into to preserve the work you've done on this repository.

I don't know if we have the means currently to display content in different languages, but storing on a branch would be the best place for any potential future language support.

Thank you!

**Pull request closed without merging**
